services:
  nginx:
    image: nginx:alpine
    container_name: stream-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-network
      - back_back-network
      - front_front-network

  certbot:
    image: certbot/certbot
    container_name: stream-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    networks:
      - nginx-network
      - back_back-network
      - front_front-network

networks:
  nginx-network:
    driver: bridge
  back_back-network:
    external: true
  front_front-network:
    external: true
