services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=https://freetvchannels.online/api
    restart: unless-stopped
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
