version: '3.8'

services:
  front-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=https://freetvchannels.online/api
    restart: unless-stopped
    networks:
      - stream-network

networks:
  stream-network:
    external: true
    name: stream-network
